### ISSUE TITLE
l1nk is not user friendly as a CLI program

### ISSUE THREAD

**Issue by farooqkz** [FarhadHP/l1nk#3]
users working with command line usually like to send needed inputs of a program using command line arguments, and about output of program, Un*x users and un*x like users like to have a clear output so they can use the program for shell scripting, etc. at all this would be fine:
```
$ l1nk http://long_url/
http://short_url
```
You may wish to study [The Art of Unix Programming](http://www.catb.org/esr/writings/taoup/) book if you are not familiar with Un*x culture, philosophy, norms of its community, etc(I did not study it ;) )

**Comment by farooqkz** [comment]
You may use Python's `sys.argv`

**Comment by farhadhp** [comment]
read it -> http://l1nk.ir/n2YjK

**Comment by farhadhp** [comment]
**+ UPDATED**

**Comment by farooqkz** [comment]
Yet it doesn't have a clear output which can be used easily for scripting, etc as other un*x programs and tools are.
